"""Authoritative version and generated release-file helpers."""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_FILE = Path("src/demail/__init__.py")
INNO_VERSION_FILE = Path("installer/version.iss")
DEPLOY_SPEC = Path("pysidedeploy.spec")
CHANGELOG_FILE = Path("CHANGELOG.md")

SEMVER_PATTERN = re.compile(r"(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)")
VERSION_ASSIGNMENT = re.compile(r'^__version__ = "([^"]+)"$', re.MULTILINE)
FILE_VERSION_ARGUMENT = re.compile(r"--file-version=\S+")
PRODUCT_VERSION_ARGUMENT = re.compile(r"--product-version=\S+")


@dataclass(frozen=True, order=True)
class Version:
    """A strict three-part semantic version."""

    major: int
    minor: int
    patch: int

    def __str__(self) -> str:
        return f"{self.major}.{self.minor}.{self.patch}"

    @property
    def windows(self) -> str:
        return f"{self}.0"


def parse_version(value: str) -> Version:
    """Parse a strict major.minor.patch version without prefixes or suffixes."""
    if not SEMVER_PATTERN.fullmatch(value):
        raise ValueError(f"Invalid version {value!r}; expected major.minor.patch")
    major, minor, patch = (int(part) for part in value.split("."))
    return Version(major, minor, patch)


def read_version(root: Path = ROOT) -> Version:
    """Read the one authoritative version from the runtime package."""
    source = (root / VERSION_FILE).read_text(encoding="utf-8")
    match = VERSION_ASSIGNMENT.search(source)
    if match is None:
        raise ValueError(f"No __version__ assignment in {root / VERSION_FILE}")
    return parse_version(match.group(1))


def next_version(current: Version, requested: str) -> Version:
    """Resolve patch, minor, major, or an exact newer semantic version."""
    if requested == "patch":
        candidate = Version(current.major, current.minor, current.patch + 1)
    elif requested == "minor":
        candidate = Version(current.major, current.minor + 1, 0)
    elif requested == "major":
        candidate = Version(current.major + 1, 0, 0)
    else:
        candidate = parse_version(requested)
    if candidate <= current:
        raise ValueError(f"New version {candidate} must be newer than {current}")
    return candidate


def render_inno_version(version: Version) -> str:
    """Render the generated Inno Setup version include."""
    return (
        "; Generated by tools/versioning.py. Do not edit by hand.\n"
        f'#define MyAppVersion "{version}"\n'
        f'#define MyAppVersionQuad "{version.windows}"\n'
    )


def render_deploy_spec(source: str, version: Version) -> str:
    """Replace the generated Nuitka Windows version arguments."""
    if not FILE_VERSION_ARGUMENT.search(source):
        raise ValueError("Deployment spec is missing --file-version")
    if not PRODUCT_VERSION_ARGUMENT.search(source):
        raise ValueError("Deployment spec is missing --product-version")
    source = FILE_VERSION_ARGUMENT.sub(f"--file-version={version.windows}", source)
    return PRODUCT_VERSION_ARGUMENT.sub(f"--product-version={version.windows}", source)


def release_heading(version: Version, released: date) -> str:
    return f"## {version} - {released.isoformat()}"


def add_changelog_entry(
    source: str,
    version: Version,
    notes: list[str],
    *,
    released: date | None = None,
) -> str:
    """Insert one new release entry before the existing history."""
    heading = release_heading(version, released or date.today())
    if re.search(rf"^## {re.escape(str(version))}(?:\s|$)", source, re.MULTILINE):
        raise ValueError(f"Version history already contains {version}")
    first_entry = re.search(r"^## ", source, re.MULTILINE)
    if first_entry is None:
        raise ValueError("Version history has no existing release entry")
    normalized = [note.strip() for note in notes if note.strip()]
    if not normalized:
        normalized = ["Release notes pending."]
    entry = heading + "\n\n" + "\n".join(f"- {note}" for note in normalized) + "\n\n"
    return source[: first_entry.start()] + entry + source[first_entry.start() :]


def write_generated_files(root: Path = ROOT, version: Version | None = None) -> None:
    """Regenerate every derived version surface from the authority."""
    resolved = version or read_version(root)
    (root / INNO_VERSION_FILE).write_text(render_inno_version(resolved), encoding="utf-8")
    spec_path = root / DEPLOY_SPEC
    spec_path.write_text(
        render_deploy_spec(spec_path.read_text(encoding="utf-8"), resolved),
        encoding="utf-8",
    )


def validate_generated_files(root: Path = ROOT) -> list[str]:
    """Return descriptions of stale or missing generated version surfaces."""
    version = read_version(root)
    errors: list[str] = []
    inno_path = root / INNO_VERSION_FILE
    if not inno_path.is_file() or inno_path.read_text(encoding="utf-8") != render_inno_version(
        version
    ):
        errors.append(str(INNO_VERSION_FILE))
    spec_path = root / DEPLOY_SPEC
    try:
        rendered = render_deploy_spec(spec_path.read_text(encoding="utf-8"), version)
    except (FileNotFoundError, ValueError):
        errors.append(str(DEPLOY_SPEC))
    else:
        if rendered != spec_path.read_text(encoding="utf-8"):
            errors.append(str(DEPLOY_SPEC))
    return errors


def bump(
    requested: str,
    notes: list[str],
    *,
    root: Path = ROOT,
    released: date | None = None,
) -> Version:
    """Advance the authoritative version and its generated release surfaces."""
    current = read_version(root)
    candidate = next_version(current, requested)
    changelog_path = root / CHANGELOG_FILE
    changelog = add_changelog_entry(
        changelog_path.read_text(encoding="utf-8"), candidate, notes, released=released
    )
    version_path = root / VERSION_FILE
    source = version_path.read_text(encoding="utf-8")
    version_path.write_text(
        VERSION_ASSIGNMENT.sub(f'__version__ = "{candidate}"', source, count=1),
        encoding="utf-8",
    )
    changelog_path.write_text(changelog, encoding="utf-8")
    write_generated_files(root, candidate)
    return candidate
